In [1]:
import pandas as pd
import os
import re
import ast

# Extraccion de secuencias conservadas

In [2]:
files = os.listdir('../Data/concensus_seq/')

expr = r".*\.fasta$"
files = [cadena for cadena in files if re.search(expr, cadena)]
files[0:3]

['concensus_sequence_20G.fasta',
 'concensus_sequence_23C.fasta',
 'concensus_sequence_20J.fasta']

In [3]:
def extract_seq(df):
    lst_seq = []
    for i,j in zip(df.Variante, df.RegionesConservadas):
        
        for filename in files:
            #Relacionar ID con archivo
            if filename == 'concensus.fasta':
                ID = 'Global'
                file =  filename
            else:
                ID = filename.replace('concensus_sequence_', '').replace('.fasta', '')
                file =  filename

            # Cargar e identificar la secuencia concenso
            if ID == i: 
                 with open('../Data/concensus_seq/' + filename) as file:
                     content = file.read()
                     lst_j = ast.literal_eval(j)
                     lst_j.sort()
                     
                     seq = content[lst_j[0]-1:lst_j[len(lst_j)-1]]
                     lst_seq.append(seq)
    return lst_seq

In [4]:
def preprocessing(df):
    lst_headers = []
    for i, j in zip(df.RegionesConservadas, df.Variante): 
        x = i.replace('[', '').replace(']', '').split(', ')
        y = '>'+ j + ':' +x[0] + '-' + x[len(x)-1]
        lst_headers.append(y)
    df['Headers'] = lst_headers
    return df

In [5]:
df_t = pd.read_csv('../Data/RegionesConsecutivasConservadasTimes.tsv', sep = '\t')
df_t = preprocessing(df_t)

df_t['Seq'] = extract_seq(df_t)
df_t

,Variante,RegionesConservadas,Headers,Seq
0,Global,"[31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 4...",>Global:31-173,ACCAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAACGAACT...
1,Global,"[175, 176, 177, 178, 179, 180, 181, 182, 183, ...",>Global:175-200,TCTATCTTCTGCAGGCTGCTTACGGT
2,Global,"[205, 206, 207, 208, 209]",>Global:205-209,TCCGT
3,Global,"[211, 212, 213, 214, 215, 216, 217, 218, 219, ...",>Global:211-221,TTGCAGCCGAT
4,Global,"[224, 225, 226, 227, 228, 229, 230, 231, 232, ...",>Global:224-223,ATCAGCACATCTAGGTTT
...,...,...,...,...
164,"(2023-07-01,2023-09-06]","[29776, 29777, 29778, 29775]",">(2023-07-01,2023-09-06]:29776-29775",TAGG
165,"(2023-07-01,2023-09-06]","[29824, 29825, 29826, 29827, 29828, 29829, 298...",">(2023-07-01,2023-09-06]:29824-29823",AGCTGCCTATATGGAAGAGCCCTAATGTGTAAAATTAATTTTAGTA...
166,"(2023-07-01,2023-09-06]","[29856, 29857, 29858, 29859, 29860, 29861, 298...",">(2023-07-01,2023-09-06]:29856-29855",TTAATAGCTTCTTAG
167,"(2023-07-01,2023-09-06]","[29863, 29864, 29865, 29866, 29867]",">(2023-07-01,2023-09-06]:29863-29867",AGAAT
168,"(2023-07-01,2023-09-06]","[29871, 29872, 29873, 29874, 29875, 29876, 298...",">(2023-07-01,2023-09-06]:29871-29903",AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

In [6]:
df_v = pd.read_csv('../Data/RegionesConsecutivasConservadasSinFoldVariants.tsv', sep = '\t')
df_v = preprocessing(df_v)

df_v['Seq'] = extract_seq(df_v)
df_v

,Variante,RegionesConservadas,Headers,Seq
0,Global,"[31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 4...",>Global:31-173,ACCAACCAACTTTCGATCTCTTGTAGATCTGTTCTCTAAACGAACT...
1,Global,"[175, 176, 177, 178, 179, 180, 181, 182, 183, ...",>Global:175-200,TCTATCTTCTGCAGGCTGCTTACGGT
2,Global,"[205, 206, 207, 208, 209]",>Global:205-209,TCCGT
3,Global,"[211, 212, 213, 214, 215, 216, 217, 218]",>Global:211-218,TTGCAGCC
4,Global,"[228, 229, 230, 231, 232, 233, 234]",>Global:228-234,CACATCT
...,...,...,...,...
586,recombinant,"[29760, 29761, 29752, 29753, 29754, 29755, 297...",>recombinant:29760-29759,ATCGAGTGTA
587,recombinant,"[29763, 29764, 29765, 29766, 29767, 29768, 297...",>recombinant:29763-29778,AGTGAACAATGCTAGG
588,recombinant,"[29824, 29825, 29826, 29827, 29828, 29829, 298...",>recombinant:29824-29823,AGCTGCCTATATGGAAGAGCCCTAATGTGTAAAATTAATTTTAGTA...
589,recombinant,"[29859, 29860, 29861, 29862, 29863]",>recombinant:29859-29863,TAGGA
590,recombinant,"[29871, 29872, 29873, 29874, 29875, 29876, 298...",>recombinant:29871-29903,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

# GeneraciÃ³n de FASTA

In [7]:
with open('../Data/FastaPredict/conserved_regions_UTR_time.fasta', 'w') as f:
    for header, seq in zip(df_t.Headers, df_t.Seq):
        f.write(header + '\n')
        f.write(seq + '\n')
        
with open('../Data/FastaPredict/conserved_SinFold_regions_UTR_variants.fasta', 'w') as f:
    for header, seq in zip(df_v.Headers, df_v.Seq):
        f.write(header + '\n')
        f.write(seq + '\n')